samplesheet:         "docs/samplesheet.csv"
reference:           "resources/NC_000962.3.fa"
genbank:             "resources/NC_000962.3.gb"
features:            "resources/NC_000962.3.gff3"
background_variants: "resources/mykrobe_background_variant_vcfs.tar.gz"
full_panel:          "docs/who-panel.tsv"
panel_kmer_size:     21
grades: # grading levels to build panels for
  - 2
containers:
  base:      "docker://bash:5.1"
  fastq_dl:  "docker://quay.io/biocontainers/fastq-dl:1.0.6--hdfd78af_1"
  clockwork: "docker://quay.io/mbhall88/clockwork/fe62f00"
