samplesheet:         "docs/samplesheet.csv"
reference:           "resources/NC_000962.3.fa"
genbank:             "resources/NC_000962.3.gb"
features:            "resources/NC_000962.3.gff3"
background_variants: "resources/mykrobe_background_variant_vcfs.tar.gz"
full_panel:          "docs/who-panel.tsv"
panel_kmer_size:     21
grades: # grading levels to build panels for
  - 2
containers:
  base:      "docker://bash:5.1"
  fastq_dl:  "docker://quay.io/biocontainers/fastq-dl:1.0.6--hdfd78af_1"
  clockwork: "docker://quay.io/mbhall88/clockwork:fe62f00"
  mykrobe:   "docker://quay.io/mbhall88/mykrobe:b6d0f37"
  fastp:     "docker://quay.io/biocontainers/fastp:0.23.2--h79da9fb_0"
  seqkit:    "docker://quay.io/biocontainers/seqkit:2.2.0--h9ee0642_0"
  python:    "docker://python:3.10.4-slim-bullseye"